---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 31031.
--- DateTime: 2026/1/17 11:13
---

-- 1.参数列表
-- 1.1.优惠券id
local voucherId = ARGV[1]
-- 1.2.用户id
local userId = ARGV[2]

-- 2.数据key
-- 2.1.库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 2.2.订单key
local orderKey = 'seckill:order:' .. voucherId

-- 3.资格判断
-- 3.1.判断库存是否充足
local stock = tonumber(redis.call('get', stockKey))
if(not stock or stock <= 0)
then
    return 1 -- 库存不足标记
end
-- 3.2.判断用户是否已经购买过
if(redis.call('sismember', orderKey, userId) == 1)
then
    return 2 --重复下单标记
end

-- 4.扣减库存 + 记录用户
redis.call('decr', stockKey) -- 库存-1
redis.call('sadd', orderKey, userId) -- 记录用户已下单

return 0 -- 秒杀成功标记
